[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = [
  "cd backend",
  "pip install -r requirements_standalone.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
