# Nixpacks configuration for Railway
# Tells Railway to use Python and ignore Docker

[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = [
  "cd backend",
  "pip install --no-cache-dir -r requirements_standalone.txt"
]

[phases.build]
cmds = ["echo 'Build complete - Ready for deployment'"]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
PORT = "$PORT"
PYTHONUNBUFFERED = "1"
