[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]
[build.buildContext]
dir = "backend"
[deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
