name: Build Android APK

on:
  push:
    branches: [ main ]
    paths:
      - 'android-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'android-app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: |
        cd android-app
        chmod +x gradlew || true

    - name: Build with Gradle
      run: |
        cd android-app
        ./gradlew assembleRelease --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android-app/app/build/outputs/apk/release/*.apk
        retention-days: 30

    - name: Create Release Info
      run: |
        echo "## APK Build Successful" >> $GITHUB_STEP_SUMMARY
        echo "Download the APK from the artifacts section" >> $GITHUB_STEP_SUMMARY
        echo "Build Date: $(date)" >> $GITHUB_STEP_SUMMARY
