name: Generate Gradle Wrapper
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Generate Gradle Wrapper
        run: |
          cd android-app
          gradle wrapper --gradle-version=8.2
          
      - name: Commit and push wrapper files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add android-app/gradle/wrapper/
          git add android-app/gradlew
          git add android-app/gradlew.bat
          git diff --staged --quiet || git commit -m "Auto-generate Gradle wrapper files"
          git push
