name: Generate Gradle Wrapper
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Download and Setup Gradle 8.2
        run: |
          cd android-app
          wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip -q gradle-8.2-bin.zip
          ./gradle-8.2/bin/gradle wrapper --gradle-version=8.2
          rm -rf gradle-8.2 gradle-8.2-bin.zip
          
      - name: Commit and push wrapper files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add android-app/gradle/wrapper/
          git add android-app/gradlew
          git add android-app/gradlew.bat
          git diff --staged --quiet || git commit -m "Auto-generate Gradle wrapper files"
          git push
